apiVersion: v1
kind: ConfigMap
metadata:
  name: servers-configmap
data:
  # property-like keys; each key maps to a simple value
  MYSQL_USER: admin
  MYSQL_DATABASE: phonebook
  MYSQL_DATABASE_HOST: mysql-service.default.svc.cluster.local
  # file-like keys
